language: php

## Run on container environment
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## Addons used by this package
addons:
  code_climate:
    repo_token: ${CC_TOKEN}

## Services used by this package
services:
  - mysql
  - postgresql

## List all PHP versions to test with
php:
  - 5.6
  - 7.0
  - 7.1

## Define all ENV vars to test with
env:
  - LARAVEL_VERSION="5.0.*"
  - LARAVEL_VERSION="5.1.*"
  - LARAVEL_VERSION="5.2.*"
  - LARAVEL_VERSION="5.3.*"
  - LARAVEL_VERSION="5.4.*"

matrix:
  fast_finish: true
  include:
    ## mysql laravel lts build
    - php: 5.6
      env: LARAVEL_VERSION="5.1.*" DB_TYPE="mysql"
    ## mysql laravel latest build
    - php: 7.1
      env: LARAVEL_VERSION="5.4.*" DB_TYPE="mysql"
    ## pgsql laravel lts build
    - php: 5.6
      env: LARAVEL_VERSION="5.1.*" DB_TYPE="pgsql"
    ## pgsql laravel latest build
    - php: 7.1
      env: LARAVEL_VERSION="5.4.*" DB_TYPE="pgsql"

## Run Scripts before Install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS notifer;'
  - psql -c 'create database notifer;' -U postgres

## Install Dependencies
install:
  - composer self-update
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer require laravel/framework:${LARAVEL_VERSION} --no-update --no-interaction
  - composer install --prefer-dist --no-interaction

## Run Scripts before Tests
before_script:
  - composer dump-autoload -o

## Run test Scripts
script:
  - vendor/bin/phpunit

## Run Scripts after Tests
after_script:
  - vendor/bin/test-reporter
  - export CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"
  - export CI_PULL_REQUEST="$TRAVIS_PULL_REQUEST"
  - export CI_BRANCH="$TRAVIS_BRANCH"
  - vendor/bin/coveralls -v

## Send Build Notifications to Slack
notifications:
  slack: astrotomic:CnF7P2xaZuJTJ4VzNOy6ksDH
